### ISSUE TITLE
unmet peer dependency warnings using yarn

### ISSUE THREAD

**Issue by CharleeWa** [btd/rollup-plugin-visualizer#129]
**Version**
"rollup-plugin-visualizer": "^5.6.0",

**Steps to reproduce**
Run yarn add something. Also for remove.

**What is expected?**
No warnings

**What is actually happening?**
unmet peer dependency warnings.

<img width="647" alt="截屏2022-09-26 17 55 39" src="https://user-images.githubusercontent.com/22477554/192248076-1447797c-2a4c-443b-bdc7-1f80b3480e65.png">

**Comment by btd** [comment]
Well do you have rollup in your dependencies?

**Comment by CharleeWa** [comment]
> Well do you have rollup in your dependencies?

No, rollup is installed as an indirect dependency, I don't know why rollup is installed, the warning is gone, but I don't want to do that.

**Comment by btd** [comment]
If you do not use rollup directly do not install it directly. If you use vite or other rollup based builder you already have it. This warning is because in this plugin i stated that it should be used by rollup in peerDependencies (and i stated that it is optional dependency to do not cause its installation), but you do not have it your dependencies (at least direct one). If everything works, i suggest to just ignore the warning.
