### ISSUE TITLE
Multiple representations of data in one screen

### ISSUE THREAD

**Issue by jessekelly881** [btd/rollup-plugin-visualizer#135]
A clear and concise description of what you want to happen. If it is change to template, provide the picture of your current template.

It would be nice to be able to have multiple representations of data at once. E.g Sunburst, Network, Tree all in one view. Or possible using tabs to switch between views.

**Comment by btd** [comment]
Can you explain how you will use it?

**Comment by hamedbaatour** [comment]
@btd having all views in one HTML file would be helpful with a new template an option like `template: "all"`

but for now, can we at least get the ability to pass an array to the `template` property in order to generate multiple separate HTML file for each template?

```js
[
    visualizer({
     template: [ "sunburst" , "treemap" , "network" ]
    }),
]
```

by the way btd, thanks for creating such an awesome plugin 👍🏻!

**Comment by btd** [comment]
Sorry guys, but i do not add any fancy features to the plugin. I am trying to keep it as minumum as possible to make support easier for me. This is not first time somebody asked about file with several diagrams, but nobody said how it will be used.
To generate several files, repeat plugin with different template options.
