### ISSUE TITLE
Vite

### ISSUE THREAD

**Issue by robozb** [btd/rollup-plugin-visualizer#155]
How can I use it in Vite? It seems It shows only "normal" file sizes not the size of the bundle(dist) folder:

![image](https://user-images.githubusercontent.com/8656998/221379259-8bda615b-b964-4d01-b208-62d114776cf1.png)

Thanks: Bela

**Comment by robozb** [comment]
I searched for like his https://www.npmjs.com/package/source-map-explorer

**Comment by Briaoeuidhtns** [comment]
not sure if there's a better fix, but using the `sourcemap` option and emabling sourcemaps in vite seems to give accurate bundle sizes

**Comment by btd** [comment]
To be honest i did not really understood what you are asking for.
If it is about sizes. Yes sizes shown will never much one in end bundle. To get more accurate results you need to use sourcemap option.
This is extremely rare an issue when you need so precise sizes. Treemap do not show sizes by default because of this. 
This plugin works when you want to find what is taking space in bundle. Just looking on biggest rectangle. It is not reporting tool.

**Comment by robozb** [comment]
I found the proper answer for this task: 

https://www.npmjs.com/package/source-map-explorer

vite.config.js
--------------
```
...
  build: {
    sourcemap: true
  }
...
```
And after the buil you can run this from the package.json: npm run analyze
```
  "scripts": {
    "analyze": "source-map-explorer dist/assets/*.js  --no-border-checks ",
  },
```
