### ISSUE TITLE
Feature request: Zoom functionality

### ISSUE THREAD

**Issue by rottmann** [btd/rollup-plugin-visualizer#50]
A zoom like webpack-bundle-analyzer would be nice, to better view the small parts of a treemap.

**Comment by btd** [comment]
Yea, i thought about it. Not yet sure how it could look.

**Comment by btd** [comment]
Hey, i added pretty basic zoom. I need to mention i was not implemented it in a way WBA doing this. 
I first looked how it was implemented in WBA and it was not a proper zoom but just scaling. This means small nodes still will not shown when you zoom in.
I first tried to do the same and understand it will be useless as like zoom just for zoom because you will not be able to see small (or hidden nodes).
So instead of this i found interesting example of treemap zoom at observable where zoomed not increase its visual size - this makes it possible to see small nodes and zoom to them later.
So i just published 3.1 with zoom in treemap only. 
Feedback welcomed.

**Comment by rottmann** [comment]
Thank you, for me ok, now i can see the subparts better.

**Comment by fabiospampinato** [comment]
Is it possible to change how the zoom feature works? Coming from webpack-bundle-analyzer zoom here seems almost unusable for large projects, I just can't see the name of things. In webpack-bundle-analyzer clicking on a rectangle makes that fill up the entire screen basically, it doesn't just make it marginally/arbitrarily bigger, which seems to work a lot better, plus you can zoom in and out of arbitrary points of the chart, that solves the problem entirely in edge cases where there are still so many files that you can't see them clearly enough.
