### ISSUE TITLE
gzip/brotli size with sourcemap

### ISSUE THREAD

**Issue by hsablonniere** [btd/rollup-plugin-visualizer#72]
Hey @btd, thanks very much for your tool :wink: :clap:

I just tried the new gzip/brotli feature.

* When I enable sourcemap, the gzip/brotli sizes are empty.
* When I disable sourcemap, I get sizes but they seems to be based on the source before minification etc...

My build is here: https://github.com/CleverCloud/clever-components/blob/new-cdn-build/rollup-cdn.config.js and it uses this config: https://github.com/CleverCloud/clever-components/blob/d60ce9e9047329a133c2560499aac061f465c21d/rollup-common.js#L140-L145

stats.html in your emails

**Comment by btd** [comment]
Hi, thanks for detailed bug report. 
Gzip/brotli currently used transformed sources. They are not even treeshaken (i asked in rollup issues to give access to rendered sources). 
It is not possible to get specific sizes after minification, because everything already combined to one bundle and minification works on whole bundle.

> When I enable sourcemap, the gzip/brotli sizes are empty.

**Comment by btd** [comment]
I think this is fixed
