### ISSUE TITLE
Reportes sizes don't match reality

### ISSUE THREAD

**Issue by PierBover** [btd/rollup-plugin-visualizer#96]
The reported bundle size is double the size of the actual bundle:

![image](https://user-images.githubusercontent.com/226483/113941909-9d662280-97c5-11eb-9072-932ca8a9c024.png)

![image](https://user-images.githubusercontent.com/226483/113941939-a8b94e00-97c5-11eb-9944-d924b59afd93.png)

The file deployed to Netlify with brotli compression weights 7.3kB and not 17.59kB:

![image](https://user-images.githubusercontent.com/226483/113942005-c1c1ff00-97c5-11eb-928e-fe9cddc1e84f.png)

Here's the `stats.html` file:

https://gist.github.com/PierBover/05bfd099b7d150e5fadf42e195b8ba34

**Comment by btd** [comment]
Hi, thanks for the question. I got such usually at least once a year. 

**Short answer**: yes it is different, stats file will always show bigger numbers by design and rollup functionality provided.

## Longer answer

I think first i need to explain treemap/sunburst diagram works. 

For each bundle rollup provided set of dependencies that included in bundle. Each of them contains some properties (useful for my purpose only module id and renderendLength). The first problem is exactly in property renderedLength. It is string.length of code after treeshaking. It means that if you file contains only ascii characters it will be accurate byte representation, otherwise not. This is a first place where results shows bigger numbers for individual files. At rollup 2.44 were added functionality to get treeshaked code (i sent this PR) and sooner or later i will fix this to use byte size. 

Returning to treemap. After all individual files gathered it starts to compute numbers for top directories until root. Meaning that bundle size shown is a sum of every single file size. This is a second biggest difference from actual size. It is not possible with rollup only to get individual file sizes after whole bundle transformation (read it after for example minification with terser). For this at the beginning we added `sourcemap` option, which get sizes from sourcemap. But it is still number of characters, but at least after all transformations.

Plugin order is matter also. For `sourcemap` option it is important to include plugin to be last in plugins array. Without sourcemap it is not that critical, but still you can miss some individual transformations.

The last i think need to add about gzip and brotli size, before rollup 2.44 these numbers where based on real files in your FS, i just read them put through gzip/brotli and show byte size. Now it is using treeshaked code for size estimation.

And at the end of all this mess. It is still OK. You need to understand whole purpose of this plugin. This plugin allows you to visually see biggest/repeated parts of your bundle for further optimizations. **This plugin is not representation of your filesystem**. 

Let me know if you have more questions.

**Comment by marcofugaro** [comment]
@btd what about adding an option to hide file sizes? 

If as you say

> This plugin allows you to visually see biggest/repeated parts of your bundle for further optimizations. **This plugin is not representation of your filesystem.**

Then I'd like an option to hide file sizes as they are confusing if they don't match.

<img src="https://user-images.githubusercontent.com/7217420/114758354-28fb2880-9d5d-11eb-8960-b7aa8e831aff.png" width="300" />

^ The tooltip would show only the percentage ideally.

**Comment by btd** [comment]
That makes sense, i will think about it

**Comment by btd** [comment]
I will close this one in favor of #98

**Comment by smalllong** [comment]
Still. it is very unintuitive that comments are contributing to the size in visualizer, although they won't contribute to the final minified file, which is misleading. Hope the visualizer can visualize based on output file rather than source file

**Comment by btd** [comment]
@smalllong you can try to use `sourcemap` option, it will use generated from code sourcemap. But still it is not 100% accurate (but close).

**Comment by dzegarra** [comment]
In my case, not even using sourcemap I get a close approximation of the sizes. 
Actual file size: 93Kb
Reported by visualizer: 194Kb

I'm working on a simple proof-of-concept with Vite, preact (no TS), preact/hooks, and @mui/material. 

But the visualizer gives me an idea of the proportion each lib takes. The percentages are very useful.  Thanks @btd .

**Comment by SCWR** [comment]
@btd Hello 感谢你的付出，我遇到一个问题。我使用最新版本，报告好像展示了无树摇的大小，跟实际文件大小不一致。请问是我设置问题还是？
```
npm create vite
# react + ts
cd test
npm i
```
```ts
// APP.ts
import { useState, useEffect } from 'react';
import reactLogo from './assets/react.svg';
import viteLogo from '/vite.svg';
// import * as _ from 'lodash-es';
// import _ from 'lodash-es';
import {
  isEmpty,
  isEqual,
  debounce,
  sortBy,
  defaultsDeep,
  chunk,
  size,
  throttle,
  get,
  differenceWith,
  unionWith,
  isNil,
  keyBy,
  flatMap,
  isNumber,
  cloneDeep,
  last,
  isString,
  maxBy,
  set,
  random,
} from 'lodash-es';
import './App.css';

function App() {
  const [count, setCount] = useState(0);
  useEffect(() => {
    // _.isEmpty([]);
    // _.isEqual(1, 2);
    isEmpty([]);
    isEqual(1, 2);
    debounce(() => {}, 250, { maxWait: 1000 });
    throttle(() => {}, 250, { trailing: false });
    const users = [
      { user: 'fred', age: 48 },
      { user: 'barney', age: 36 },
      { user: 'fred', age: 40 },
      { user: 'barney', age: 34 },
    ];

    sortBy(users, [
      function (o) {
        return o.user;
      },
    ]);
    defaultsDeep({ a: { b: 2 } }, { a: { b: 1, c: 3 } });
    chunk(['a', 'b', 'c', 'd'], 2);
    size({ a: 1, b: 2 });
    const object = { a: [{ b: { c: 3 } }] };
    get(object, 'a[0].b.c');
    set(object, 'a[0].b.c', 4);
    differenceWith(
      [
        { x: 1, y: 2 },
        { x: 2, y: 1 },
      ],
      [{ x: 1, y: 2 }],
      isEqual
    );
    unionWith(
      [
        { x: 1, y: 2 },
        { x: 2, y: 1 },
      ],
      [{ x: 1, y: 2 }],
      isEqual
    );
  }, []);
  isNil('');
  keyBy(
    [
      { dir: 'left', code: 97 },
      { dir: 'right', code: 100 },
    ],
    'dir'
  );
  flatMap([1, 2], n => [n, n]);
  isNumber(1);
  cloneDeep({});
  last([1, 2, 3]), isString(1);
  maxBy([{ n: 1 }, { n: 2 }], 'n');
  random(false);
  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount(count => count + 1)}>count is {count}</button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">Click on the Vite and React logos to learn more</p>
    </>
  );
}

export default App;
```
```
//vite.config.ts
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { visualizer } from 'rollup-plugin-visualizer';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  build: {
    sourcemap: true,
    rollupOptions: {
      plugins: [
        visualizer({
          open: true,
          template: 'treemap',
          gzipSize: true,
          brotliSize: true,
          // sourcemap: true,
        }),
      ],
      output: {
        manualChunks: {
          'react-vendor': ['react', 'react-dom'],
          lodash: ['lodash-es'],
        },
      },
    },
  },
});
```
![image](https://github.com/btd/rollup-plugin-visualizer/assets/8925282/f2fe8db5-cade-40da-8aeb-8e48055e42fb)
![image](https://github.com/btd/rollup-plugin-visualizer/assets/8925282/c35be9e5-34a4-4236-862b-7edf7fbc05af)

**Comment by btd** [comment]
Add fix for sourcemap to 5.11.0

**Comment by liukj98** [comment]
After enabling sourcemap, the plugin report size is indeed very close to the actual package size, but the treemap view can only see the final packaged file and cannot view the volume size of other packages that the file depends on，why?

**Comment by SimonEast** [comment]
> After enabling `sourcemap`, the plugin report size is indeed very close to the actual package size, but the treemap view can only see the final packaged file and cannot view the volume size of other packages that the file depends on，why?

I get the same as @liukj98. That provides no useful information.

I'm really struggling to see the point of this plugin if the numbers are incorrect due to including things like comments, and don't take into account any minification. In that case it would provide only a very approximate percentage taken up by each file.

**Comment by oliviertassinari** [comment]
We should keep this issue open, no? It's not a solved problem.

**Comment by Verthon** [comment]
Still happens even on the latest 7.0.1 version - maybe it's worth reopening?

Vite says `dist/static/js/tanstack.GSVu6L39.js                         40.76 kB │ gzip:  11.62 kB │ map:   181.72 kB`

<img width="461" height="208" alt="Image" src="https://github.com/user-attachments/assets/4e923c29-e084-4d2a-84c6-23c9102dd12e" />

**Comment by SimonEast** [comment]
I switched to **[Sonda](https://sonda.dev/)** as it displays nice visualisations along with accurate file sizes of all the modules in your bundle.
